### ISSUE TITLE
Install Beard

### ISSUE THREAD

**Issue by ryzy** [million12/docker-typo3-flow-neos-abstract#19]
Beard v. 1.1.4 now supports also GitHub, so it'd be quite handy to have it in the container by default.

**Comment by baschny** [comment]
I think this is already included now, right?

**Comment by ryzy** [comment]
True, resolved by https://github.com/million12/docker-typo3-flow-neos-abstract/commit/f935dd148f96d88bcb2d75a787d5945dc258e5f6, https://github.com/million12/docker-typo3-flow-neos-abstract/commit/8b4cf3401495d0cb08e25e131c0c8dabe3e3ccc5 and https://github.com/million12/docker-typo3-flow-neos-abstract/commit/f4b78f62520505e96c35d13d9314bf88b021010e
