### ISSUE TITLE
Nginx is loading endlessly

### ISSUE THREAD

**Issue by DavidSporer** [million12/docker-typo3-flow-neos-abstract#23]
Hi,

thank you for that awesome work you're doing!
I've built a docker image with my own Flow project and everything seems to be fine. Database migrations run through, nginx is running (log output) but if I try to open the page which is running under passcreator.local:8080 in my case, it's loading for a minute or so and then telling me that the site is not available.
Can you guys help me how to analyze what's going wrong?

Thanks,
David

**Comment by DavidSporer** [comment]
Sorry, stupid me...
I was using the wrong IP...

**Comment by ryzy** [comment]
No worries, good that you've figured it out ;)
