### ISSUE TITLE
Make deployment ssh key available for 'www' user

### ISSUE THREAD

**Issue by ryzy** [million12/docker-typo3-flow-neos-abstract#5]
The issue occurs when I use private repository and I provided a private ssh key, whereas pubkey is added to repository deployment keys.

Now, when I log in as a 'www' user, I cannot do e.g. git pull because that ssh key is (or might) not be available to 'www' user. It is available during `docker build` process, but not when I log in directly as 'www' user.

It gets even more complicated if I use /data volume inside another container (e.g. side ssh container) and try to do git pull there. Then the key is completely missing and I cannot do much w/o tedious manual process to make it work (i.e. configuring manually the keys).

Solution:
* make the priv ssh key available to 'www' user in its home directory /data/www. Then no matter what, inside the same container or side container with mounted volume user www will have access to it.
* configure it, so it's added to keys used by git (.bash_profile?)

**Comment by Duske** [comment]
Hey, thanks a lot for this awesome docker image! :)
Concerning your first suggestion for a solution, would this be an adequate way to gain access to the ssh key as 'www' user?

```
COPY gh-repo-key /data/www/.ssh/id_rsa
COPY gh-repo-key.pub /data/www/.ssh/id_rsa.pub
RUN \
	chmod 600 /data/www/.ssh/id_rsa && \
	chmod 600 /data/www/.ssh/id_rsa.pub
```

**Comment by ryzy** [comment]
Resolved in https://github.com/million12/docker-typo3-flow-neos-abstract/commit/016369a0752fb6c4fe0c56f1d10a15af8a40e273
