### ISSUE TITLE
Nginx vhost: rewrite rules break resources links in Neos 1.3 (current master)

### ISSUE THREAD

**Issue by ryzy** [million12/docker-typo3-flow-neos-abstract#8]
This issue is visible with Neos master branch.
Apparently [these rewrite rules](https://github.com/million12/docker-typo3-flow-neos-abstract/blob/master/container-files/etc/nginx/conf.d/typo3-flow-rewrites.conf) are no longer necessary.

This is breaking change... not sure yet how to make it work for 1.3 and before 1.3.

**Comment by dimaip** [comment]
Maybe do smth like Rens suggested?:
```
if (-f /Users/rens/Sites/Flow/$project/Packages/Application/TYPO3.Media/Classes/TYPO3/Media/TypeConverter/ImageInterfaceConverter.php) {
			break;
		}
```
